name: workflow1

on: pull_request


jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
#   super-lint:
#     # Name the Job
#     name: Lint code base
#     # Set the type of machine to run on
#     runs-on: ubuntu-latest

#     steps:
#       # Checks out a copy of your repository on the ubuntu-latest machine
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Runs the Super-Linter action
#       - name: Run Super-Linter
#         uses: github/super-linter@v3
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    
    env:
      SCHEME: "GIthubActionTestProject"
      DEVICE: "iPhone 12"
      PROJECT: "GIthubActionTestProject.xcodeproj"
    
    runs-on: macOS-latest
    
    steps:
    
    - name: Checkout project
      uses: actions/checkout@v1
    
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app
    
    - name: Build Application
      run: |
        set -eo pipefail && xcodebuild build-for-testing \
                             -project $PROJECT \
                             -scheme $SCHEME \
                             -destination "platform=iOS Simulator,name=$DEVICE,OS=14.2"
            
  unit_test:

    name: testing iPhone 12
    
    env:
      SCHEME: "GIthubActionTestProject"
      DEVICE: "iPhone 12"
      PROJECT: "GIthubActionTestProject.xcodeproj"

    runs-on: macOS-latest

    steps:

    - name: Checkout project
      uses: actions/checkout@v1

    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app

    - name: Run unit tests
      run: |
        set -eo pipefail && xcodebuild test-without-building \
                              -project $PROJECT \
                              -scheme $SCHEME \
                              -destination "platform=iOS Simulator,name=$DEVICE,OS=14.2"
